apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service  # ⭐ Key name referenced in Ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Environment=dev"
    alb.ingress.kubernetes.io/timeout: "60" 
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000