name: Deploy to Minikube

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.14.0
      with:
        minikube version: 'v1.35.0'
        kubernetes version: 'v1.33.0'
        github token: ${{ secrets.GITHUB_TOKEN }}
        driver: docker
        addons: ingress,dashboard

    - name: Start Minikube
      run: |
        minikube start
        minikube status
        minikube addons enable ingress 
        kubectl cluster-info

    - name: Deploy Application
      run: |
        kubectl apply -f manifests/configmap.yaml
        kubectl apply -f manifests/app-secrets.yaml

    - name: Deploy MongoDB
      run: |
        kubectl apply -f manifests/mongo-db.yaml
        kubectl wait --for=condition=Ready pod -l app=mongo --timeout=120s

    - name: Deploy Application
      run: |
        kubectl apply -f manifests/deployment.yaml
        kubectl wait --for=condition=Available deployment/app-deployment --timeout=180s
        kubectl apply -f manifests/service.yaml
        kubectl apply -f manifests/ingress.yaml

    - name: Verify
      run: kubectl get all,ingress

